name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - name: Download dependencies
        run: nix develop -ic sbt update
      - name: Check format
        run: nix develop -ic sbt checkFormat
      - name: Lint
        run: nix develop -ic sbt lint
      - name: Test
        run: nix develop -ic sbt testCoverage
      - name: Mutation test
        run: nix develop -ic sbt mutationTest
